
add_newline = true  # Inserts a blank line between shell prompts
command_timeout = 1000  # Change command timeout from 500 to 1000 ms
format = """$env_var $all"""  # Add custom formatting before other stuff

# Drop ugly default prompt characters
[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '
vicmd_symbol = '[V](bold green) '

# Shows the current username
[env_var.USER]
format = '[$env_value](bold green) '
variable = "USER"
disabled = false

# Shows an icon depending on what device it is running on
[env_var.STARSHIP_DEVICE]
format = 'on [$env_value](bold yellow)'
variable = "STARSHIP_DEVICE"
disabled = false

# ---

# Shows an icon depending on what distro it is running on
[env_var.STARSHIP_DISTRO]
format = '[$env_value](bold blue) '
variable = "STARSHIP_DISTRO"
disabled = false

# Shows the hostname
[hostname]
ssh_only = false
format = "[$hostname](bold purple) "
disabled = false

# Shows current directory
[directory]
truncation_length = 2
truncation_symbol = "…/"
home_symbol = " ~"
read_only_style = "197"
read_only = "  "
format = "at [$path]($style)[$read_only]($read_only_style) "

# Disable some modules that aren't needed anymore
[username]
disabled = false

[vagrant]
disabled = false

[docker_context]
disabled = false

[helm]
disabled = false

[python]
disabled = false

[nodejs]
disabled = false

[ruby]
disabled = false

[terraform]
disabled = false
